#!/usr/bin/env bash

tmp=$1
existing=$2

if [ -f $existing ]; then
        diff --suppress-common-lines $tmp $existing ;
	if [ $? -ne 0 ]; then
		echo "file $tmp doesn't match $existing";
		#  exit 1;
	fi;
fi;
cp "$tmp" "$existing";
