output_path="${SQUEALGEN_OUTPUT_PATH:-squealgen}"

# Extract version from package.yaml for embedding in generated output
version=$(grep '^version:' package.yaml | sed 's/version: *//')

cat > "${output_path}" <<'EOF'
#!/bin/bash
# NB: this file is generated by mksquealgen.sh, don't edit it directly

if [ "$#" -lt 3 ]; then
    echo "Usage: squealgen DBNAME MODULENAME SCHEMA [IMPORTS]";
    exit 1;
fi
DBNAME=$1
MODULENAME=$2
SCHEMA=$3
IMPORTS=$4 # this can be empty.
EOF

echo 'PSQLCMD=${PSQLCMD:-psql}' >> "${output_path}"
echo "version='${version}'" >> "${output_path}"
echo '$PSQLCMD -X -d "${DBNAME}" -v chosen_schema="${SCHEMA}" -v modulename="${MODULENAME}" -v extra_imports="${IMPORTS}" -v squealgen_version="${version}" <<"EOF"' >> "${output_path}"
cat squealgen.sql >> "${output_path}"
echo "EOF" >> "${output_path}"
chmod 755 "${output_path}"
