
cat > squealgen <<'EOF'
#!/bin/bash
# NB: this file is generated by mksquealgen.sh, don't edit it directly

DBNAME=$1
MODULENAME=$2
SCHEMA=$3
EOF

echo 'hi'
echo 'psql ${DBNAME} -v chosen_schema=${SCHEMA} -v modulename=${MODULENAME} <<"EOF"' >> squealgen
cat squealgen.sql >> squealgen
echo "EOF" >> squealgen
