name:                squealgen
version:             0.1.0.0
github:              "mwotton/squealgen"
license:             BSD3
author:              "Mark Wotton"
maintainer:          "mwotton@gmail.com"
copyright:           "2020 Mark Wotton"

extra-source-files:
- README.md
- ChangeLog.md
- squealgen
# - squealgen.sql

# Metadata used when publishing your package
synopsis:            generate squeal types from an existing database
category:            Database
description:         Please see the README on GitHub at <https://github.com/mwotton/squealgen#readme>

dependencies:
- base >= 4.7
- squeal-postgresql >= 0.9.2.0

library:
  source-dirs: src
  exposed-modules:
  - Paths_squealgen
  - LTree

data-files:
- squealgen.sql

tests:
  tests:
    main: Spec.hs
    source-dirs: test
    default-extensions:
    - DataKinds
    - DeriveGeneric
    - OverloadedLabels
    - FlexibleContexts
    - TypeApplications
    - TypeOperators
    - GADTs

    dependencies:
    - bytestring
    - hspec
    - hspec-expectations-lifted
    - squeal-postgresql
    - unliftio
    - generics-sop
    - squealgen
    - text
    - tmp-postgres >= 1.34.1.0
    - containers
    - network-ip
    - iproute

    # temp until merge
    - postgresql-binary
    - mtl

    build-tools:
    - hspec-discover
