-- | This code was generated by squealgen.
-- |
-- | Generation parameters:
-- | Schema: public
-- | Module: Enums.Public
-- |
-- | Edit if you know how it got made and are willing to own it now.
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedLabels #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE GADTs #-}
{-# OPTIONS_GHC -fno-warn-unticked-promoted-constructors #-}

module Enums.Public where
import Squeal.PostgreSQL
import GHC.TypeLits(Symbol)





type DB = '["public" ::: Schema]

type Schema = Join Tables (Join Views (Join Enums (Join Functions (Join Composites Domains))))
-- Trigger contract: Triggers is generated metadata and is not composed into Schema.
-- enums
type PGtraffic_light = 'PGenum
  '["Red", "Yellow", "Green"]
-- decls
type Enums =
  ('["traffic_light" ::: 'Typedef PGtraffic_light] :: [(Symbol,SchemumType)])

type Composites =
  ('[] :: [(Symbol,SchemumType)])

-- schema
type Tables = ('[
   "lights" ::: 'Table LightsTable]  :: [(Symbol,SchemumType)])

-- defs
type LightsColumns = '["light" ::: 'NoDef :=> 'NotNull PGtraffic_light]
type LightsConstraints = '[]
type LightsTable = LightsConstraints :=> LightsColumns

-- VIEWS
type Views = 
  '["lights_v" ::: 'View LightsVView]

type LightsVView = 
  '["light" ::: 'Null PGtraffic_light]

-- functions
type Functions = 
  '[  ]
-- Omitted function signatures: none
-- Omitted SRF signatures: none
type Domains = '[]

-- Check-constraint fallback notes: none

-- triggers
-- Trigger contract: Triggers is generated metadata and is not composed into Schema.
type Triggers = 
  '[]

-- Trigger fallback notes: none
