-- | This code was generated by squealgen.
-- |
-- | Generation parameters:
-- | Schema: public
-- | Module: CompositeForeignKeys.Public
-- | Version: 2.0.0
-- |
-- | Edit if you know how it got made and are willing to own it now.
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedLabels #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE GADTs #-}
{-# OPTIONS_GHC -fno-warn-unticked-promoted-constructors #-}

module CompositeForeignKeys.Public where
import Squeal.PostgreSQL
import GHC.TypeLits(Symbol)





type DB = '["public" ::: Schema]

type Schema = Join Tables (Join Views (Join Enums (Join Functions (Join Composites Domains))))
-- Trigger contract: Triggers is generated metadata and is not composed into Schema.
-- enums

-- decls
type Enums =
  ('[] :: [(Symbol,SchemumType)])

type Composites =
  ('[] :: [(Symbol,SchemumType)])

-- schema
type Tables = ('[
   "table_one" ::: 'Table TableOneTable
  ,"table_two" ::: 'Table TableTwoTable]  :: [(Symbol,SchemumType)])

-- defs
type TableOneColumns = '["table_two_id" ::: 'NoDef :=> 'Null PGint4
  ,"col_one" ::: 'NoDef :=> 'NotNull PGint4
  ,"col_two" ::: 'NoDef :=> 'NotNull PGint4]
type TableOneConstraints = '["table_one_pkey" ::: 'PrimaryKey '["col_one","col_two"]]
type TableOneTable = TableOneConstraints :=> TableOneColumns

type TableTwoColumns = '["table_two_id" ::: 'NoDef :=> 'Null PGint4
  ,"col_one" ::: 'NoDef :=> 'Null PGint4
  ,"col_two" ::: 'NoDef :=> 'Null PGint4]
type TableTwoConstraints = '["table_two_fkey" ::: 'ForeignKey '["col_one","col_two"] "public" "table_one" '["col_one","col_two"]]
type TableTwoTable = TableTwoConstraints :=> TableTwoColumns

-- VIEWS
type Views = 
  '[]

-- functions
type Functions = 
  '[  ]

-- Omitted function signatures: none
-- Omitted SRF signatures: none
type Domains = '[]

-- Check-constraint fallback notes: none

-- triggers
-- Trigger contract: Triggers is generated metadata and is not composed into Schema.
type Triggers = 
  '[]

-- Trigger fallback notes: none
