-- | This code was generated by squealgen.
-- |
-- | Generation parameters:
-- | Schema: public
-- | Module: Composites.Public
-- | Version: 0.2.0.0
-- |
-- | Edit if you know how it got made and are willing to own it now.
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedLabels #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE GADTs #-}
{-# OPTIONS_GHC -fno-warn-unticked-promoted-constructors #-}

module Composites.Public where
import Squeal.PostgreSQL
import GHC.TypeLits(Symbol)





type DB = '["public" ::: Schema]

type Schema = Join Tables (Join Views (Join Enums (Join Functions (Join Composites Domains))))
-- Trigger contract: Triggers is generated metadata and is not composed into Schema.
-- enums

-- decls
type Enums =
  ('[] :: [(Symbol,SchemumType)])
type PGclump = 'PGcomposite '["foo" ::: 'NotNull PGtext, "bar" ::: 'NotNull PGint4]
type PGvarclump = 'PGcomposite '["vfoo" ::: 'NotNull PGtext, "vbar" ::: 'NotNull PGint4, "vbaz" ::: 'NotNull PGtext]
type Composites =
  ('["clump" ::: 'Typedef PGclump,
  "varclump" ::: 'Typedef PGvarclump] :: [(Symbol,SchemumType)])

-- schema
type Tables = ('[
   "dummy" ::: 'Table DummyTable]  :: [(Symbol,SchemumType)])

-- defs
type DummyColumns = '["i" ::: 'NoDef :=> 'Null PGint4]
type DummyConstraints = '[]
type DummyTable = DummyConstraints :=> DummyColumns

-- VIEWS
type Views = 
  '[]

-- functions
type Functions = 
  '[  ]

-- Omitted function signatures: none
-- Omitted SRF signatures: none
type Domains = '[]

-- Check-constraint fallback notes: none

-- triggers
-- Trigger contract: Triggers is generated metadata and is not composed into Schema.
type Triggers = 
  '[]

-- Trigger fallback notes: none
