-- | This code was generated by squealgen.
-- |
-- | Generation parameters:
-- | Schema: public
-- | Module: Basic.Public
-- |
-- | Edit if you know how it got made and are willing to own it now.
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedLabels #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE GADTs #-}
{-# OPTIONS_GHC -fno-warn-unticked-promoted-constructors #-}

module Basic.Public where
import Squeal.PostgreSQL
import GHC.TypeLits(Symbol)





type DB = '["public" ::: Schema]

type Schema = Join Tables (Join Views (Join Enums (Join Functions (Join Composites Domains))))
-- Trigger contract: Triggers is generated metadata and is not composed into Schema.
-- enums

-- decls
type Enums =
  ('[] :: [(Symbol,SchemumType)])

type Composites =
  ('[] :: [(Symbol,SchemumType)])

-- schema
type Tables = ('[
   "foo" ::: 'Table FooTable
  ,"foo2" ::: 'Table Foo2Table]  :: [(Symbol,SchemumType)])

-- defs
type FooColumns = '["id" ::: 'Def :=> 'NotNull PGint4
  ,"name" ::: 'NoDef :=> 'Null PGtext]
type FooConstraints = '[]
-- | Primary foo table.
type FooTable = FooConstraints :=> FooColumns

type Foo2Columns = '["id" ::: 'Def :=> 'NotNull PGint4
  ,"limited" ::: 'NoDef :=> 'NotNull (PGvarchar 12)]
type Foo2Constraints = '[]
type Foo2Table = Foo2Constraints :=> Foo2Columns

-- VIEWS
type Views = 
  '[]

-- functions
type Functions = 
  '[  ]

-- Omitted function signatures: none
-- Omitted SRF signatures: none
type Domains = '[]

-- Check-constraint fallback notes: none

-- triggers
-- Trigger contract: Triggers is generated metadata and is not composed into Schema.
type Triggers = 
  '[]

-- Trigger fallback notes: none
