name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    name: ${{ matrix.os }}-${{ matrix.ghc }}-stack
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        stack: ["latest"]
        ghc: ["8.8.3"]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - name: install postgresql on ubuntu
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt install postgresql-10

    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}
        enable-stack: true

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Ensure rebuild
      run : |
        touch squealgen.sql

    - name: Test
      run: |
        PATH=/usr/lib/postgresql/10/bin:$PATH make test
