name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  cabal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PostgreSQL client tools
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql

      - name: Add PostgreSQL bin to PATH
        run: echo "$(pg_config --bindir)" >> "$GITHUB_PATH"

      - name: Setup Haskell
        id: setup-haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.6.6'
          cabal-version: '3.10.2.0'

      - name: Cache cabal store
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ steps.setup-haskell.outputs.ghc-version }}-${{ hashFiles('cabal.project', 'squealgen.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.setup-haskell.outputs.ghc-version }}-

      - name: Update package list
        run: cabal update

      - name: Build
        run: cabal build all

      - name: Test
        run: cabal test --test-show-details=direct
